### ISSUE TITLE
PMIX clients time out on start-up using PRRTE as launcher

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/prrte#254]
Thank you for taking the time to submit an issue!

## Background information

Launch of PMIX clients fails/times-out with latest PRRTE

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

master @ d54aa74d7bb06b3a1d567ed5e59a8d4a31ef2adf

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

3.1.4 release and master @ 80f80b17589232eee49f6807afda2b853aee51d2

### Please describe the system on which you are running

* Operating system/version: CentOS 7.5
* Computer hardware: x86_64
* Network type: IB

-----------------------------

## Details of the problem

Programs launched on > 4 nodes (4 might just be the point at which I'm seeing the issue and have no specific inherent meaning) under PBS/Torque time out with

```shell
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[12106,0],0] on node cn099
  Remote daemon: [[12106,0],1] on node cn002

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
```

Same programs launch immediately using Open-MPI 4.0.x as PMIx server.

**Comment by rhc54** [comment]
@tonycurtis I believe this is fixed but don't have a ready way to test it - can you please give the head of PRRTE master a try and let me know (close this issue if it works)?

**Comment by tonycurtis** [comment]
> On Oct 21, 2019, at 9:24 AM, Ralph Castain <notifications@github.com> wrote:
> 
> @tonycurtis <https://github.com/tonycurtis> I believe this is fixed but don't have a ready way to test it - can you please give the head of PRRTE master a try and let me know (close this issue if it works)?
> 

Looking good
Thanks
Tony

**Comment by rhc54** [comment]
Thanks!

**Comment by tonycurtis** [comment]
Still happening on runs > 4 nodes (wasn't able to get >4 nodes earlier).  Same program running fine with OpenMPI as launcher.

```shell
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[34392,0],0] on node cn097
  Remote daemon: [[34392,0],5] on node cn010

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
```

**Comment by rhc54** [comment]
Nuts - will look tomorrow night when have more time

**Comment by tonycurtis** [comment]
Well, actually, we're apparently switching over on this cluster fully to SLURM next Monday and it's the only PBS/Torque system I have access to at the moment, so I won't be able to test after that.

**Comment by jjhursey** [comment]
(we should probably re-open this issue to keep track of it)

@tonycurtis Can you try with Open MPI v3.1.4 on that machine?
Open MPI hit a similar issue with its launcher in the v3 series that does not exist in the v4 or master series. I wonder if it might be a similar root cause (maybe a similar eventual fix).
 * https://github.com/open-mpi/ompi/issues/7087#issuecomment-541092006

**Comment by tonycurtis** [comment]
3.1.4 worked with 8 nodes

**Comment by tonycurtis** [comment]
Launch hanging with Open-MPI github master @ ecd990a67cbc5ce85328202858c90aae4d7fe122 (any number of processes) & PMIx master.  No timeout message so far, just sits there...

**Comment by jjhursey** [comment]
I don't seem to have the proper rights to re-open this issue. But we should do so so we don't lose track of this.

**Comment by tonycurtis** [comment]
Just managed to test with new SLURM setup: same error with 8 nodes

**Comment by tonycurtis** [comment]
Looked into this again (we now have SLURM everywhere).

`prted` is leaking memory.  Just triggered the oom-killer on all the non-launch nodes.

**Comment by tonycurtis** [comment]
Looks like fixed

**Comment by rhc54** [comment]
Woohoo! Thanks!
